- name: installing maven
  ansible.builtin.package:
    name: maven
    state: present
    
- name: mvn clean package
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app