- name: Install python packages
  ansible.builtin.dnf:
    name: "{{item}}" 
    state: present
  loop:
  - python36
  - gcc
  - python3-devel


  # - name: install python36 gcc python3-devel -y #above this code same
  #   ansible.builtin.command: dnf install python36 gcc python3-devel -y



- name: Install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app